# .air.toml inside cmd/auth
root = "../../"
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/auth.exe ."  # <-- point to current folder
bin = "tmp/auth.exe"                # <-- must include .exe
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
